# Travis CI configuration file.
# @link https://travis-ci.org/

# For use with the Twenty Sixteen WordPress theme
# @link https://github.com/WordPress/twentysixteen/

# Declare project language and PHP versions to test against.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
php:
    # Current $required_php_version for WordPress: 5.2.4
    - "5.2"
